export enum NoteCommands {
  GET_NOTE_LIST = 100,
  ADD_NEW_NOTE = 101,
  GET_NOTE_DETAILS = 102,
  UPDATE_NOTE_TITLE = 103,
  UPDATE_NOTE_CONTENT = 104,
  UPDATE_NOTE_COLOR = 105,
  SHIFT_NOTE = 106,
  DELETE_NOTE = 107,
}

export default NoteCommands
