name: Deploy on VPS Lite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Get the version from package.json
        id: get_version
        run: echo "VERSION=$(node -p -e \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Create tag
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload builder-debug.yml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/builder-debug.yml
          asset_name: builder-debug.yml
          asset_content_type: application/octet-stream

      - name: Upload builder-effective-config.yaml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/builder-effective-config.yaml
          asset_name: builder-effective-config.yaml
          asset_content_type: application/octet-stream

      - name: Upload latest.yml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/latest.yml
          asset_name: latest.yml
          asset_content_type: application/octet-stream

      - name: Upload workmemo-setup.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/workmemo-setup-${{ env.VERSION }}.exe
          asset_name: workmemo-setup-${{ env.VERSION }}.exe
          asset_content_type: application/octet-stream

      - name: Upload workmemo-setup.exe.blockmap
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/workmemo-setup-${{ env.VERSION }}.exe.blockmap
          asset_name: workmemo-setup-${{ env.VERSION }}.exe.blockmap
          asset_content_type: application/octet-stream
