name: Release app on Windows

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:win

      - name: Get the version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: Release v${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false

      - name: Upload builder-debug.yml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/builder-debug.yml
          asset_name: builder-debug.yml
          asset_content_type: application/octet-stream

      - name: Upload builder-effective-config.yaml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/builder-effective-config.yaml
          asset_name: builder-effective-config.yaml
          asset_content_type: application/octet-stream

      - name: Upload latest.yml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/latest.yml
          asset_name: latest.yml
          asset_content_type: application/octet-stream

      - name: Upload workmemo-setup.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/workmemo-setup-${{ steps.package-version.outputs.current-version }}.exe
          asset_name: workmemo-setup-${{ steps.package-version.outputs.current-version }}.exe
          asset_content_type: application/octet-stream

      - name: Upload workmemo-setup.exe.blockmap
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/workmemo-setup-${{ steps.package-version.outputs.current-version }}.exe.blockmap
          asset_name: workmemo-setup-${{ steps.package-version.outputs.current-version }}.exe.blockmap
          asset_content_type: application/octet-stream
